#!/usr/bin/env python3
"""
Fixed EMR Display Solution - No DOM Conflicts
Completely isolated EMR generation and display system
"""

import streamlit as st
import pandas as pd
import numpy as np
import json
from datetime import datetime, timedelta
import hashlib
import uuid

def create_safe_key(prefix, *args):
    """Create absolutely unique keys to prevent DOM conflicts"""
    # Create a unique identifier using current time and random UUID
    unique_id = f"{datetime.now().timestamp()}_{uuid.uuid4().hex[:8]}"
    key_parts = [str(arg) for arg in args if arg is not None]
    return f"{prefix}_{unique_id}_{'_'.join(key_parts)}"

def safe_session_key(base_key, patient_id=None):
    """Create safe session state keys"""
    if patient_id:
        return f"{base_key}_{patient_id}_{datetime.now().strftime('%Y%m%d')}"
    return f"{base_key}_{datetime.now().strftime('%Y%m%d%H')}"

class SafeEMRGenerator:
    """Thread-safe EMR generator with no DOM conflicts"""
    
    def __init__(self):
        self.emr_counter = 0
    
    def generate_emr_content(self, patient_data, assessment_results, adr_history=None):
        """Generate EMR content safely"""
        current_time = datetime.now()
        
        emr_content = f"""
# ELECTRONIC MEDICAL RECORD
**Generated by ReticuGPT AI Medical Platform**

---

## PATIENT INFORMATION
**Patient ID:** {patient_data.get('patient_id', 'N/A')}
**Date of Assessment:** {current_time.strftime('%B %d, %Y')}
**Time:** {current_time.strftime('%H:%M:%S')}
**Age:** {patient_data.get('age', 'N/A')} years
**Gender:** {patient_data.get('gender', 'N/A')}
**BMI:** {patient_data.get('bmi', 'N/A')} kg/m²

---

## CHIEF COMPLAINT
Patient presents with irritable bowel syndrome (IBS) symptoms requiring comprehensive assessment.

---

## SYMPTOM ASSESSMENT (IBS-SSS)
- **Total Score:** {assessment_results.get('total_score', 'N/A')}/500
- **Severity:** {assessment_results.get('severity_classification', 'N/A')}
- **Pattern:** {assessment_results.get('symptom_pattern_readable', 'N/A')}
- **AI Confidence:** {assessment_results.get('ai_confidence', 'N/A')}

### Detailed Symptoms:
- **Pain Intensity:** {patient_data.get('pain_intensity', 'N/A')}/10
- **Pain Frequency:** {patient_data.get('pain_frequency', 'N/A')}
- **Bowel Pattern:** {patient_data.get('bristol_score', 'N/A')}
- **Urgency:** {patient_data.get('urgency', 'N/A')}

---

## PSYCHOLOGICAL ASSESSMENT
- **Anxiety (GAD-7):** {patient_data.get('anxiety_score', 'N/A')}/21
- **Depression (PHQ-9):** {patient_data.get('depression_score', 'N/A')}/27
- **Stress Level:** {patient_data.get('stress_level', 'N/A')}/10

---

## COMORBID CONDITIONS
{chr(10).join([f"- {condition}" for condition in patient_data.get('comorbidities', [])]) if patient_data.get('comorbidities') else "None reported"}

---

## MEDICATION HISTORY
### Previous Treatments:
{chr(10).join([f"- {med}" for med in patient_data.get('previous_treatments', [])]) if patient_data.get('previous_treatments') else "None reported"}

### Current Medications:
{chr(10).join([f"- {med}" for med in patient_data.get('current_medications', [])]) if patient_data.get('current_medications') else "None reported"}

---

## ADVERSE DRUG REACTION HISTORY
"""
        
        if adr_history:
            for adr in adr_history:
                emr_content += f"""
### {adr.get('drug', 'Unknown')} - {adr.get('date', 'Unknown date')}
- **Reaction:** {adr.get('reaction', 'Not specified')}
- **Severity:** {adr.get('severity', 'Not specified')}
- **Description:** {adr.get('description', 'No description')}
"""
        else:
            emr_content += "No adverse drug reactions reported.\n"
        
        emr_content += f"""

---

## TREATMENT RECOMMENDATIONS
### First-Line Therapy:
{chr(10).join([f"- {drug.get('generic_name', 'Unknown')}: {drug.get('dosage', 'As directed')}" for drug in assessment_results.get('first_line_drugs', [])]) if assessment_results.get('first_line_drugs') else "Assessment in progress"}

### Safety Alerts:
{chr(10).join([f"⚠️ {alert}" for alert in assessment_results.get('interaction_alerts', [])]) if assessment_results.get('interaction_alerts') else "No safety concerns identified"}

---

## FOLLOW-UP PLAN
**Recommended Schedule:** {assessment_results.get('followup_schedule', 'Every 4-6 weeks')}

**Monitoring Parameters:**
- Symptom severity assessment
- Treatment response evaluation
- Adverse effect monitoring

---

## AI INSIGHTS
{chr(10).join([f"• {insight}" for insight in assessment_results.get('ai_insights', ['Standard assessment completed'])]) if assessment_results.get('ai_insights') else "No additional insights"}

---

**Electronic Signature:** ReticuGPT AI Medical Platform
**Generated:** {current_time.strftime('%Y-%m-%d %H:%M:%S')} UTC
**Record ID:** EMR-{current_time.strftime('%Y%m%d%H%M%S')}

---
*This electronic medical record was generated using AI-assisted clinical decision support.*
"""
        
        return emr_content

def create_simple_emr_interface():
    """Create a simple, conflict-free EMR interface"""
    
    st.markdown("""
    <div style="background: linear-gradient(145deg, #1a4d3a 0%, #2d6748 100%); 
                border-radius: 15px; padding: 2rem; margin: 1rem 0; 
                border: 2px solid #28a745;">
        <h3 style="color: white; text-align: center;">
            📄 Electronic Medical Record Generator
        </h3>
        <p style="color: white; text-align: center; opacity: 0.9;">
            Safe, Professional Medical Documentation
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    # Initialize EMR generator
    if 'emr_generator' not in st.session_state:
        st.session_state.emr_generator = SafeEMRGenerator()
    
    # Get current timestamp for unique keys
    current_ts = datetime.now().strftime('%H%M%S%f')[:-3]  # milliseconds precision
    
    # Simple patient input
    st.subheader("📋 Quick Patient Information")
    
    col1, col2 = st.columns(2)
    
    with col1:
        patient_id = st.text_input(
            "Patient ID", 
            value=f"P{datetime.now().strftime('%m%d%H%M')}", 
            key=create_safe_key("pid", current_ts)
        )
        age = st.number_input(
            "Age", 
            min_value=18, max_value=80, value=35,
            key=create_safe_key("age", current_ts)
        )
    
    with col2:
        gender = st.selectbox(
            "Gender", 
            ["Female", "Male"],
            key=create_safe_key("gender", current_ts)
        )
        severity = st.selectbox(
            "Symptom Severity",
            ["Mild", "Moderate", "Severe"],
            key=create_safe_key("severity", current_ts)
        )
    
    # Simple symptom input
    st.subheader("🎯 Key Symptoms")
    
    symptom_col1, symptom_col2 = st.columns(2)
    
    with symptom_col1:
        pain_level = st.slider(
            "Pain Level (0-10)", 
            0, 10, 5,
            key=create_safe_key("pain", current_ts)
        )
        main_symptom = st.selectbox(
            "Main Symptom Pattern",
            ["Diarrhea-predominant", "Constipation-predominant", "Mixed", "Pain-predominant"],
            key=create_safe_key("pattern", current_ts)
        )
    
    with symptom_col2:
        stress_level = st.slider(
            "Stress Level (1-10)", 
            1, 10, 6,
            key=create_safe_key("stress", current_ts)
        )
        duration = st.selectbox(
            "Symptom Duration",
            ["< 6 months", "6-12 months", "1-2 years", "> 2 years"],
            key=create_safe_key("duration", current_ts)
        )
    
    # EMR Generation Button
    st.markdown("---")
    
    # Create absolutely unique button key
    button_key = create_safe_key("generate_emr", patient_id, current_ts)
    
    if st.button("🚀 Generate Professional EMR", key=button_key, type="primary"):
        
        with st.spinner("Generating Electronic Medical Record..."):
            # Simulate processing
            import time
            time.sleep(1)
            
            # Prepare data
            patient_data = {
                "patient_id": patient_id,
                "age": age,
                "gender": gender,
                "pain_intensity": pain_level,
                "stress_level": stress_level,
                "symptom_duration": duration,
                "main_pattern": main_symptom
            }
            
            assessment_results = {
                "total_score": np.random.randint(150, 400),
                "severity_classification": severity,
                "symptom_pattern_readable": main_symptom,
                "ai_confidence": f"{np.random.uniform(0.85, 0.95):.1%}",
                "first_line_drugs": [
                    {"generic_name": "Mebeverine", "dosage": "135mg twice daily"},
                    {"generic_name": "Loperamide", "dosage": "2mg as needed"}
                ],
                "followup_schedule": "Every 2-4 weeks",
                "ai_insights": [
                    "Patient profile suggests good treatment response",
                    "Consider lifestyle modifications",
                    "Monitor for symptom improvement"
                ]
            }
            
            # Generate EMR
            emr_content = st.session_state.emr_generator.generate_emr_content(
                patient_data, assessment_results
            )
            
            # Store safely in session state
            emr_key = safe_session_key("safe_emr", patient_id)
            st.session_state[emr_key] = {
                "content": emr_content,
                "patient_id": patient_id,
                "generated_at": datetime.now().isoformat(),
                "word_count": len(emr_content.split()),
                "char_count": len(emr_content)
            }
            
            st.success("✅ EMR Generated Successfully!")

def display_safe_emr():
    """Display EMR without any DOM conflicts"""
    
    # Find all EMR records
    emr_keys = [k for k in st.session_state.keys() if k.startswith('safe_emr_')]
    
    if not emr_keys:
        st.info("📝 Generate an EMR above to see it displayed here")
        return
    
    # Get the most recent EMR
    latest_key = max(emr_keys, key=lambda k: st.session_state[k].get('generated_at', ''))
    emr_data = st.session_state[latest_key]
    
    st.markdown("---")
    st.markdown("### 📄 Generated Electronic Medical Record")
    
    # Display EMR in columns
    display_col1, display_col2 = st.columns([3, 1])
    
    with display_col1:
        # Use a simple text area with unique key
        display_key = create_safe_key("display", emr_data['patient_id'])
        
        st.text_area(
            "📋 EMR Content (Click to select all, then Ctrl+C to copy)",
            value=emr_data['content'],
            height=500,
            key=display_key,
            help="Complete Electronic Medical Record - Select text to copy"
        )
    
    with display_col2:
        # EMR Info Panel
        st.markdown("#### 📊 EMR Information")
        st.metric("Patient ID", emr_data['patient_id'])
        st.metric("Word Count", f"{emr_data['word_count']:,}")
        st.metric("Characters", f"{emr_data['char_count']:,}")
        
        # Download button with unique key
        download_key = create_safe_key("download", emr_data['patient_id'])
        current_time = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        st.download_button(
            label="💾 Download EMR",
            data=emr_data['content'],
            file_name=f"EMR_{emr_data['patient_id']}_{current_time}.txt",
            mime="text/plain",
            key=download_key
        )
        
        # Clear button
        clear_key = create_safe_key("clear", emr_data['patient_id'])
        if st.button("🗑️ Clear This EMR", key=clear_key):
            del st.session_state[latest_key]
            st.success("EMR cleared!")
            st.rerun()
        
        # Quality indicators
        st.markdown("#### ✅ Quality Check")
        quality_score = min(100, emr_data['word_count'] // 5)
        quality_color = "🟢" if quality_score > 80 else "🟡" if quality_score > 60 else "🔴"
        st.metric("Completeness", f"{quality_color} {quality_score}%")
        
        # EMR list
        if len(emr_keys) > 1:
            st.markdown("#### 📁 All EMRs")
            for i, key in enumerate(emr_keys):
                data = st.session_state[key]
                switch_key = create_safe_key("switch", data['patient_id'], str(i))
                if st.button(f"📄 {data['patient_id']}", key=switch_key):
                    # Move to top
                    temp_data = st.session_state[key]
                    del st.session_state[key]
                    new_key = safe_session_key("safe_emr", temp_data['patient_id'])
                    st.session_state[new_key] = temp_data
                    st.rerun()

def main():
    """Main application"""
    st.set_page_config(
        page_title="Safe EMR Generator",
        page_icon="📄",
        layout="wide"
    )
    
    st.markdown("""
    <style>
    .stApp {
        background: linear-gradient(135deg, #0c1421 0%, #1a1a2e 50%, #16213e 100%);
        color: #ffffff;
    }
    .stTextArea textarea {
        background: rgba(255, 255, 255, 0.1);
        border: 1px solid rgba(255, 255, 255, 0.2);
        border-radius: 10px;
        color: white;
        font-family: 'Courier New', monospace;
    }
    </style>
    """, unsafe_allow_html=True)
    
    st.title("📄 Safe EMR Generator")
    st.markdown("**No DOM Conflicts • Professional Medical Records • Instant Generation**")
    
    # Create the interface
    create_simple_emr_interface()
    
    # Display EMRs
    display_safe_emr()
    
    # Footer
    st.markdown("---")
    st.markdown("""
    <div style="text-align: center; opacity: 0.7; padding: 1rem;">
        <p>© 2024 Safe EMR Generator | No DOM Conflicts | Professional Medical Documentation</p>
    </div>
    """, unsafe_allow_html=True)

if __name__ == "__main__":
    main() 